// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ar-agahian/ice-assignment/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockITodoRepository is an autogenerated mock type for the ITodoRepository type
type MockITodoRepository struct {
	mock.Mock
}

type MockITodoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITodoRepository) EXPECT() *MockITodoRepository_Expecter {
	return &MockITodoRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *MockITodoRepository) Create(ctx context.Context, item *domain.TodoItem) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TodoItem) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITodoRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockITodoRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *domain.TodoItem
func (_e *MockITodoRepository_Expecter) Create(ctx interface{}, item interface{}) *MockITodoRepository_Create_Call {
	return &MockITodoRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockITodoRepository_Create_Call) Run(run func(ctx context.Context, item *domain.TodoItem)) *MockITodoRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.TodoItem))
	})
	return _c
}

func (_c *MockITodoRepository_Create_Call) Return(_a0 error) *MockITodoRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITodoRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.TodoItem) error) *MockITodoRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockITodoRepository) GetByID(ctx context.Context, id string) (*domain.TodoItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.TodoItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.TodoItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.TodoItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TodoItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITodoRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockITodoRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockITodoRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockITodoRepository_GetByID_Call {
	return &MockITodoRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockITodoRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockITodoRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockITodoRepository_GetByID_Call) Return(_a0 *domain.TodoItem, _a1 error) *MockITodoRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITodoRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.TodoItem, error)) *MockITodoRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITodoRepository creates a new instance of MockITodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITodoRepository {
	mock := &MockITodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
