// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockIFileStorage is an autogenerated mock type for the IFileStorage type
type MockIFileStorage struct {
	mock.Mock
}

type MockIFileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFileStorage) EXPECT() *MockIFileStorage_Expecter {
	return &MockIFileStorage_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: ctx, fileID
func (_m *MockIFileStorage) Exists(ctx context.Context, fileID string) (bool, error) {
	ret := _m.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, fileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, fileID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFileStorage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockIFileStorage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockIFileStorage_Expecter) Exists(ctx interface{}, fileID interface{}) *MockIFileStorage_Exists_Call {
	return &MockIFileStorage_Exists_Call{Call: _e.mock.On("Exists", ctx, fileID)}
}

func (_c *MockIFileStorage_Exists_Call) Run(run func(ctx context.Context, fileID string)) *MockIFileStorage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIFileStorage_Exists_Call) Return(_a0 bool, _a1 error) *MockIFileStorage_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFileStorage_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockIFileStorage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, fileID
func (_m *MockIFileStorage) Get(ctx context.Context, fileID string) ([]byte, error) {
	ret := _m.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, fileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFileStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIFileStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockIFileStorage_Expecter) Get(ctx interface{}, fileID interface{}) *MockIFileStorage_Get_Call {
	return &MockIFileStorage_Get_Call{Call: _e.mock.On("Get", ctx, fileID)}
}

func (_c *MockIFileStorage_Get_Call) Run(run func(ctx context.Context, fileID string)) *MockIFileStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIFileStorage_Get_Call) Return(_a0 []byte, _a1 error) *MockIFileStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFileStorage_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockIFileStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, file, contentType
func (_m *MockIFileStorage) Upload(ctx context.Context, file io.Reader, contentType string) (string, error) {
	ret := _m.Called(ctx, file, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) (string, error)); ok {
		return rf(ctx, file, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) string); ok {
		r0 = rf(ctx, file, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string) error); ok {
		r1 = rf(ctx, file, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFileStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockIFileStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - contentType string
func (_e *MockIFileStorage_Expecter) Upload(ctx interface{}, file interface{}, contentType interface{}) *MockIFileStorage_Upload_Call {
	return &MockIFileStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, file, contentType)}
}

func (_c *MockIFileStorage_Upload_Call) Run(run func(ctx context.Context, file io.Reader, contentType string)) *MockIFileStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(string))
	})
	return _c
}

func (_c *MockIFileStorage_Upload_Call) Return(fileID string, err error) *MockIFileStorage_Upload_Call {
	_c.Call.Return(fileID, err)
	return _c
}

func (_c *MockIFileStorage_Upload_Call) RunAndReturn(run func(context.Context, io.Reader, string) (string, error)) *MockIFileStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIFileStorage creates a new instance of MockIFileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFileStorage {
	mock := &MockIFileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
