// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIStreamPublisher is an autogenerated mock type for the IStreamPublisher type
type MockIStreamPublisher struct {
	mock.Mock
}

type MockIStreamPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStreamPublisher) EXPECT() *MockIStreamPublisher_Expecter {
	return &MockIStreamPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, stream, data
func (_m *MockIStreamPublisher) Publish(ctx context.Context, stream string, data map[string]interface{}) error {
	ret := _m.Called(ctx, stream, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, stream, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIStreamPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockIStreamPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - stream string
//   - data map[string]interface{}
func (_e *MockIStreamPublisher_Expecter) Publish(ctx interface{}, stream interface{}, data interface{}) *MockIStreamPublisher_Publish_Call {
	return &MockIStreamPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, stream, data)}
}

func (_c *MockIStreamPublisher_Publish_Call) Run(run func(ctx context.Context, stream string, data map[string]interface{})) *MockIStreamPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIStreamPublisher_Publish_Call) Return(_a0 error) *MockIStreamPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIStreamPublisher_Publish_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *MockIStreamPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStreamPublisher creates a new instance of MockIStreamPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStreamPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStreamPublisher {
	mock := &MockIStreamPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
